---
title: "meteo"
author: "Sophie Boutin"
date: "2024-06-13"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(patchwork)
```

# Import data
```{r}
setwd("~/Documents/CLE_USB_SARAH/Universite/M.Sc./Lab_and_field_work/R/meteo/")

meteo_SHB_2022 <- read_csv("meteo_SHB_2022.csv")
meteo_MTL_2022 <- read_csv("meteo_MTL_2022.csv")
meteo_QC_2022  <- read_csv("meteo_QC_2022.csv")

meteo_SHB_2022 <- meteo_SHB_2022[,c(3,5,6,7,8,10,12,14,24)]
meteo_MTL_2022 <- meteo_MTL_2022[,c(3,5,6,7,8,10,12,14,24)]
meteo_QC_2022  <- meteo_QC_2022 [,c(3,5,6,7,8,10,12,14,24)]

meteo <- rbind(meteo_SHB_2022, meteo_MTL_2022, meteo_QC_2022)

```

## Meteo all cities
```{r}
meteo <- subset(meteo, Mois == "05" | Mois == "06" | Mois == "08" | Mois == "09" | Mois == "10")

colnames(meteo) <- c("City","Date","Year","Month","Day","Max","Min","Mean","Rain")

meteo <- as.data.frame(meteo)

# Replace commas with dots in the specified column
meteo <- meteo %>%
  mutate(Max = gsub(",", ".", Max))
meteo <- meteo %>%
  mutate(Min = gsub(",", ".", Min))
meteo <- meteo %>%
  mutate(Mean = gsub(",", ".", Mean))
meteo <- meteo %>%
  mutate(Rain = gsub(",", ".", Rain))

meteo$City[meteo$City == "MCTAVISH"] <- "Montréal"
meteo$City[meteo$City == "BEAUPORT"] <- "Québec"
meteo$City[meteo$City == "SHERBROOKE"] <- "Sherbrooke"

meteo$Date  <- as.Date(meteo$Date)
meteo$City  <- as.factor(meteo$City)
meteo$Year  <- as.factor(meteo$Year)
meteo$Month <- as.factor(meteo$Month)
meteo$Day   <- as.factor(meteo$Day)
meteo$Max   <- as.numeric(meteo$Max)
meteo$Min   <- as.numeric(meteo$Min)
meteo$Mean  <- as.numeric(meteo$Mean)
meteo$Rain  <- as.numeric(meteo$Rain)

meteo$Time  <- format(as.Date(meteo$Date), "%m-%d")
```

### Meteo subsets by city
```{r}
meteo_MTL <- subset(meteo, City == "Montréal")

meteo_QC  <- subset(meteo, City == "Québec")

meteo_SHB <- subset(meteo, City == "Sherbrooke")
```

### Meteo subsets by month
#### MTL
```{r}
meteo_MTL_May      <- subset(meteo_MTL, Month == "05")

meteo_MTL_June     <- subset(meteo_MTL, (Month == "05" & Day == 31) | Month == "06")

meteo_MTL_Sept_Oct <- subset(meteo_MTL, (Month == "08" & Day == 31) | Month == "09" | Month == "10")
```

#### SHB
```{r}
meteo_SHB_May      <- subset(meteo_SHB, Month == "05")

meteo_SHB_June     <- subset(meteo_SHB, (Month == "05" & Day == 31) | Month == "06")

meteo_SHB_Sept_Oct <- subset(meteo_SHB, (Month == "08" & Day == 31) | Month == "09" | (Month == "10" & Day == "01"))
```

#### QC
```{r}
meteo_QC_May       <- subset(meteo_QC, Month == "05")

meteo_QC_Sept_Oct  <- subset(meteo_QC, (Month == "08" & Day == 31) | Month == "09" | Month == "10")
```

# Figures
## Figure Montréal
```{r}
###### MTL
# Spring MTL: 05-03 to 05-07
# Summer MTL: 06-(08,10,12-13)
# Fall MTL:   08-31 to 09-(07,09)

plot_MTL <- ggplot(meteo_MTL, aes(x=Time, y=Mean, color = City, group = City)) + 
  geom_point()+ 
  geom_line()+
  theme_bw()+
  scale_color_manual(values = "indianred3")+
  annotate("rect", xmin = "05-03", xmax = "05-07", ymin = 0, ymax = 25, alpha = 0.5, fill = "#ffb3c6")+
  annotate("rect", xmin = "06-08", xmax = "06-13", ymin = 0, ymax = 25, alpha = 0.5, fill = "#61a5c2")+
  annotate("rect", xmin = "08-31", xmax = "09-09", ymin = 0, ymax = 25, alpha = 0.5, fill = "#F29040")+
  ylab("")+
  xlab("")+
  theme(axis.text.x = element_text(angle = 90),
        axis.text = element_text(size =11),
        axis.title = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_text(size = 30))+
        #legend.position = "none")+
  # Manually add a custom legend
  annotate("text", x = 05,  y = 26.5, label = "Spring",  size = 8, color = "#ffb3c6",fontface = "bold")+
  annotate("text", x = 41,  y = 26.5, label = "Summer",  size = 8, color = "#61a5c2",fontface = "bold")+
  annotate("text", x = 96,  y = 26.5, label = "Fall",    size = 8, color = "#F29040",fontface = "bold");plot_MTL
```

## Figure Québec city
```{r}
# Spring QC:  05-(12,13,14,18,19)
# Fall QC:    09-(29,30) and 10-(01,02,05)

plot_QC <- ggplot(meteo_QC, aes(x=Time, y=Mean, color = City, group = City)) + 
  geom_point()+ 
  geom_line()+
  theme_bw()+
  scale_color_manual(values = "khaki3")+
  annotate("rect", xmin = "05-12", xmax = "05-19", ymin = 0, ymax = 25, alpha = 0.5, fill = "#ffb3c6")+
  annotate("rect", xmin = "09-29", xmax = "10-05", ymin = 0, ymax = 25, alpha = 0.5, fill = "#F29040")+
  ylab("")+
  xlab("")+
  theme(axis.text.x = element_text(angle = 90),
        axis.text = element_text(size =11),
        axis.title = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_text(size = 30))+
        #legend.position = "none")+
  # Manually add a custom legend
  annotate("text", x = 15,   y = 26.5, label = "Spring",  size = 8, color = "#ffb3c6",fontface = "bold")+
  #annotate("text", x = 42,  y = 26.5, label = "Summer",  size = 7, color = "#61a5c2",fontface = "bold")+
  annotate("text", x = 124,  y = 26.5, label = "Fall",    size = 8, color = "#F29040",fontface = "bold");plot_QC
```

## Figure Sherbrooke
```{r}
# Spring SHB: 05-09 to 05-11
# Summer SHB: 05-31 to 06-03
# Fall SHB:   09-(21,23,25,27) and 10-04
plot_SHB <- ggplot(meteo_SHB, aes(x=Time, y=Mean, color = City, group = City)) + 
  geom_point()+ 
  geom_line()+
  theme_bw()+
  scale_color_manual(values = "darkolivegreen3")+
  annotate("rect", xmin = "05-09", xmax = "05-11", ymin = 0, ymax = 25, alpha = 0.5, fill = "#ffb3c6")+
  annotate("rect", xmin = "05-31", xmax = "06-03", ymin = 0, ymax = 25, alpha = 0.5, fill = "#61a5c2")+
  annotate("rect", xmin = "09-21", xmax = "10-04", ymin = 0, ymax = 25, alpha = 0.5, fill = "#F29040")+
  ylab("")+
  xlab("")+
  theme(axis.text.x = element_text(angle = 90),
        axis.text = element_text(size =11),
        axis.title = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_text(size = 30))+
        #legend.position = "none")+
  # Manually add a custom legend
  annotate("text", x = 10,    y = 26.5, label = "Spring",  size = 8, color = "#ffb3c6",fontface = "bold")+
  annotate("text", x = 32.5,  y = 26.5, label = "Summer",  size = 8, color = "#61a5c2",fontface = "bold")+
  annotate("text", x = 119,   y = 26.5, label = "Fall",    size = 8, color = "#F29040",fontface = "bold");plot_SHB
```

### Patchwork
```{r}
meteo_all_cities <- plot_MTL / plot_QC / plot_SHB
meteo_all_cities + plot_annotation(tag_levels = "A") # 20 x 33 landscape
```


## Figures May
### MTL
```{r}
# Spring MTL: 05-03 to 05-07
plot_MTL_May <- ggplot(meteo_MTL_May, aes(x=Time, y=Mean, color = City, group = City)) + 
  geom_point()+ 
  geom_line()+
  theme_bw()+
  scale_color_manual(values = "indianred3")+
  annotate("rect", xmin = "05-03", xmax = "05-08", ymin = 0, ymax = 25, alpha = 0.5, fill = "#ffb3c6")+
  ylab("")+
  xlab("")+
  theme(axis.text.x = element_text(angle = 90),
        axis.text = element_text(size =20),
        axis.title = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_text(size = 30));plot_MTL_May
```

### QC
```{r}
# Spring QC:  05-(12,13,14,18,19)
plot_QC_May <- ggplot(meteo_QC_May, aes(x=Time, y=Mean, color = City, group = City)) + 
  geom_point()+ 
  geom_line()+
  theme_bw()+
  scale_color_manual(values = "khaki3")+
  annotate("rect", xmin = "05-12", xmax = "05-15", ymin = 0, ymax = 25, alpha = 0.5, fill = "#ffb3c6")+
  annotate("rect", xmin = "05-18", xmax = "05-20", ymin = 0, ymax = 25, alpha = 0.5, fill = "#ffb3c6")+
  ylab("")+
  xlab("")+
  theme(axis.text.x = element_text(angle = 90),
        axis.text = element_text(size =20),
        axis.title = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_text(size = 30));plot_QC_May
```


### SHB
```{r}
# Spring SHB: 05-09 to 05-11
plot_SHB_May <- ggplot(meteo_SHB_May, aes(x=Time, y=Mean, color = City, group = City)) + 
  geom_point()+ 
  geom_line()+
  theme_bw()+
  scale_color_manual(values = "darkolivegreen3")+
  annotate("rect", xmin = "05-09", xmax = "05-12", ymin = 0, ymax = 25, alpha = 0.5, fill = "#ffb3c6")+
  ylab("")+
  xlab("")+
  theme(axis.text.x = element_text(angle = 90),
        axis.text = element_text(size =20),
        axis.title = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_text(size = 30));plot_SHB_May
```


## Figures Juin
### MTL
```{r}
# Summer MTL: 06-(08,10,12-13)
plot_MTL_June <- ggplot(meteo_MTL_June, aes(x=Time, y=Mean, color = City, group = City)) + 
  geom_point()+ 
  geom_line()+
  theme_bw()+
  scale_color_manual(values = "indianred3")+
  annotate("rect", xmin = "06-08", xmax = "06-09", ymin = 0, ymax = 25, alpha = 0.5, fill = "#61a5c2")+
  annotate("rect", xmin = "06-10", xmax = "06-11", ymin = 0, ymax = 25, alpha = 0.5, fill = "#61a5c2")+
  annotate("rect", xmin = "06-12", xmax = "06-14", ymin = 0, ymax = 25, alpha = 0.5, fill = "#61a5c2")+
  ylab("")+
  xlab("")+
  theme(axis.text.x = element_text(angle = 90),
        axis.text = element_text(size =20),
        axis.title = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_text(size = 30));plot_MTL_June
```

### SHB
```{r}
# Summer SHB: 05-31 to 06-03
plot_SHB_June <- ggplot(meteo_SHB_June, aes(x=Time, y=Mean, color = City, group = City)) + 
  geom_point()+ 
  geom_line()+
  theme_bw()+
  scale_color_manual(values = "darkolivegreen3")+
  annotate("rect", xmin = "05-31", xmax = "06-04", ymin = 0, ymax = 25, alpha = 0.5, fill = "#61a5c2")+
  ylab("")+
  xlab("")+
  theme(axis.text.x = element_text(angle = 90),
        axis.text = element_text(size =20),
        axis.title = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_text(size = 30));plot_SHB_June
```


## Figures sept-oct
### MTL
```{r}
# Fall MTL:   08-31 to 09-(07,09)
plot_MTL_Sept <- ggplot(meteo_MTL_Sept_Oct, aes(x=Time, y=Mean, color = City, group = City)) + 
  geom_point()+ 
  geom_line()+
  theme_bw()+
  scale_color_manual(values = "indianred3")+
  annotate("rect", xmin = "08-31", xmax = "09-08", ymin = 0, ymax = 25, alpha = 0.5, fill = "#F29040")+
  annotate("rect", xmin = "09-09", xmax = "09-10", ymin = 0, ymax = 25, alpha = 0.5, fill = "#F29040")+
  ylab("")+
  xlab("")+
  theme(axis.text.x = element_text(angle = 90),
        axis.text = element_text(size =20),
        axis.title = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_text(size = 30));plot_MTL_Sept
```

### QC
```{r}
# Fall QC:    09-(29,30) and 10-(01,02,05)
plot_QC_Sept <- ggplot(meteo_QC_Sept_Oct, aes(x=Time, y=Mean, color = City, group = City)) + 
  geom_point()+ 
  geom_line()+
  theme_bw()+
  scale_color_manual(values = "khaki3")+
  annotate("rect", xmin = "09-29", xmax = "10-03", ymin = 0, ymax = 25, alpha = 0.5, fill = "#F29040")+
  annotate("rect", xmin = "10-05", xmax = "10-06", ymin = 0, ymax = 25, alpha = 0.5, fill = "#F29040")+
  ylab("")+
  xlab("")+
  theme(axis.text.x = element_text(angle = 90),
        axis.text = element_text(size =20),
        axis.title = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_text(size = 30));plot_QC_Sept
```


### SHB
```{r}
# Fall SHB:   09-(21,23,25,27) and 10-04
plot_SHB_Sept <- ggplot(meteo_SHB_Sept_Oct, aes(x=Time, y=Mean, color = City, group = City)) + 
  geom_point()+ 
  geom_line()+
  theme_bw()+
  scale_color_manual(values = "darkolivegreen3")+
  annotate("rect", xmin = "09-21", xmax = "09-22", ymin = 0, ymax = 25, alpha = 0.5, fill = "#F29040")+
  annotate("rect", xmin = "09-23", xmax = "09-24", ymin = 0, ymax = 25, alpha = 0.5, fill = "#F29040")+
  annotate("rect", xmin = "09-25", xmax = "09-26", ymin = 0, ymax = 25, alpha = 0.5, fill = "#F29040")+
  annotate("rect", xmin = "09-27", xmax = "09-28", ymin = 0, ymax = 25, alpha = 0.5, fill = "#F29040")+
  annotate("rect", xmin = "10-04", xmax = "10-05", ymin = 0, ymax = 25, alpha = 0.5, fill = "#F29040")+
  
  ylab("")+
  xlab("")+
  theme(axis.text.x = element_text(angle = 90),
        axis.text = element_text(size =20),
        axis.title = element_text(size = 14),
        legend.title = element_blank(),
        legend.text = element_text(size = 30));plot_SHB_Sept
```

#### Patchwork
```{r}
meteo_May <- plot_MTL_May / plot_QC_May / plot_SHB_May
meteo_May + plot_annotation(tag_levels = "A") # 20 x 33 landscape

meteo_June <- plot_MTL_June / plot_SHB_June
meteo_June + plot_annotation(tag_levels = "A")

meteo_Sept <- plot_MTL_Sept / plot_QC_Sept / plot_SHB_Sept
meteo_Sept + plot_annotation(tag_levels = "A")
```

